namespace Meck.Shared.Accela.ParserModels
{
    public class CommercialProjectCustomForm
    {
           public object HDMeatMarket { get; set; }
            public object HDAdultDayCare { get; set; }
            public object HDLodging { get; set; }
            public object HDSeafood { get; set; }
            public object HDSeafoodCapacity { get; set; }
            public object HDSeafoodUtensilTypeReusable { get; set; }
            public object HDWaterRecreation_Pool { get; set; }
            public object HDBarServiceUtensilTypeReusable { get; set; }
            public object HDOther { get; set; }
            public object RestaurantUtensilTypeReusable { get; set; }
            public object HDBarServiceCapacity { get; set; }
            public object HDBarServiceUtensilTypeDisposable { get; set; }
            public object Restaurant { get; set; }
            public object HDAdultDayCareCapacity { get; set; }
            public object HDChildDayCare { get; set; }
            public object RestaurantUtensilTypeDisposable { get; set; }
            public object HDChildDayCareCapacity { get; set; }
            public object HDOtherDescription { get; set; }
            public object RestaurantCapacity { get; set; }
            public object HDSeafoodUtensilTypeDisposable { get; set; }
            public string id { get; set; }
            public object BarService { get; set; }
            public object CurrentReviewCycle { get; set; }
            public object ClonedFromProjectNumber { get; set; }
            public object IsRTAP { get; set; }
            public object TaxJurisdiction { get; set; }
            public object RecordLocation { get; set; }
            public object PlumScopeOfWorkDescription { get; set; }
            public object CivilScopeOfWorkDescription { get; set; }
            public object ElecScopeOfWorkDescription { get; set; }
            public object OverallScopeOfWorkDescription { get; set; }
            public object MechScopeOfWorkDescription { get; set; }
            public object SecondaryRepairParkingGarage { get; set; }
            public object SpecialProvisionsType5098 { get; set; }
            public object SpecialProvisionsType5097 { get; set; }
            public object SpecialProvisionsType5096 { get; set; }
            public object SpecialProvisionsType5095 { get; set; }
            public object SpecialProvisionsType5094 { get; set; }
            public object SpecialProvisionsType5093 { get; set; }
            public object SpecialProvisionsType5092 { get; set; }
            public object SeparationHours { get; set; }
            public object PrimaryOpenParkingGarage { get; set; }
            public object SpecialProvisions { get; set; }
            public object PrimaryRepairParkingGarage { get; set; }
            public object MixedUseSeperatedNonSeparated { get; set; }
            public object PrimaryIdentifyWhatIsBeingStored { get; set; }
            public object PrimaryHighPiled { get; set; }
            public object SecondaryEnclosedParkingGarage { get; set; }
            public object SeparationException { get; set; }
            public object PrimaryEnclosedParkingGarage { get; set; }
            public object SecondaryOccupancy { get; set; }
            public object SecondaryOpenParkingGarage { get; set; }
            public object IsMixedUse { get; set; }
            public object PrimaryOccupancy { get; set; }
            public object SecondaryIdentifyWhatIsBeingStored { get; set; }
            public object OccupancyCode { get; set; }
            public object SecondaryOccupancyCode { get; set; }
            public object SecondaryHighPiled { get; set; }
            public object ShellProjectNumber { get; set; }
            public object FirstPhaseProjectNumber { get; set; }
            public object FirstPhase { get; set; }
            public object OriginalProjectNumber { get; set; }
            public object PhasedConstruction { get; set; }
            public object FirstUpfit { get; set; }
            public object ZoningZoningCode { get; set; }
            public object ZoningProposedBusiness { get; set; }
            public object ZoningPreviousBusiness { get; set; }
            public object CityAddingTreePlanting { get; set; }
            public object CityChangingDrivewayEtc { get; set; }
            public object CityAdjoinsPublicStreet { get; set; }
            public object CityNewPublicOrPrivateStreet { get; set; }
            public object CityAdding11OrMoreParkingSpace { get; set; }
            public object CityPlannedMultiFamily { get; set; }
            public object CityAddingImperviousArea { get; set; }
            public object CityZonedUrban { get; set; }
            public object CityChangingFacadeOver10Percent { get; set; }
            public object CityGradingMoreThanOneAcre { get; set; }
            public object CityBuildingOver1000SqFt { get; set; }
            public object CityBuildingOver5PercentSqFt { get; set; }
            public object CityAddingTreeProtection { get; set; }
            public object Cranes { get; set; }
            public object HasBasement { get; set; }
            public object Mezzanine { get; set; }
            public object ConstructionType { get; set; }
            public object SustainableDesign { get; set; }
            public object NumBldgsForReview { get; set; }
            public object UnlimitedPerCodeSection { get; set; }
            public object IncrUsableSpace { get; set; }
            public object Generators { get; set; }
            public object Elevators { get; set; }
            public object HighRise { get; set; }
            public object BuildingHeight { get; set; }
            public object SqFtToReview { get; set; }
            public object UnlimitedArea { get; set; }
            public object GrossSquareFeet { get; set; }
            public object NumStoriesOverallBldg { get; set; }
            public object SpecialInspections { get; set; }
            public object IncrUsableSqFt { get; set; }
            public object UPS { get; set; }
            public object AsbestosSurveyConducted { get; set; }
            public object MMFOrSPTProject { get; set; }
            public object CityCountyOwnedBldgSQFt { get; set; }
            public object PreliminaryReviewDone { get; set; }
            public string ProjectName { get; set; }
            public object ConditionalPermitApproval { get; set; }
            public object IncludesAfforableOrWorkforceHousing { get; set; }
            public object AsbestosRemoval { get; set; }
            public object BondAt50000 { get; set; }
            public object AfforableHousingUnits { get; set; }
            public object DrawingsReadyDate { get; set; }
            public object AccountNumber { get; set; }
            public object TotalNumOfSheets { get; set; }
            public object CityCountyOwnedBldg { get; set; }
            public object DemolitionPerformed { get; set; }
            public object WorkforceHousingUnits { get; set; }
            public object PreliminaryProjectNumber { get; set; }
            public object ConditionalPermitProjectNumber { get; set; }
            public object GateKeeperChecklistAdded { get; set; }
            public object PrepaidFeePaymentType { get; set; }
            public object FireNFPAType13R { get; set; }
            public object FireFirePump { get; set; }
            public object FireElevator { get; set; }
            public object FireDrawingsIncluded { get; set; }
            public object FireNFPAType13 { get; set; }
            public object FireStandpipeClassIII { get; set; }
            public object FireStandpipeClassI { get; set; }
            public object FireStandpipeClassWet { get; set; }
            public object FireStandpipe { get; set; }
            public object FirePumpNewOrExisting { get; set; }
            public object FireStandpipeClassDry { get; set; }
            public object FireSmokeDetector { get; set; }
            public object FireStandpipeClassII { get; set; }
            public object FireBuildingSprinkled { get; set; }
            public object FireFireAlarm { get; set; }
            public object FireNFPAType13D { get; set; }
            public object FireNFPANewOrExisting { get; set; }
            public string BuildingCode { get; set; }
            public string PropertyType { get; set; }
            public string ReviewType { get; set; }
            public object TypeOfWork { get; set; }
            public object EquipmentCost { get; set; }
            public object ConstructionCost { get; set; }
            public object ProjectCostTotal { get; set; }
            public object ChangeOfUseForZoning { get; set; }
            public object DownsizingSuite { get; set; }
            public object PreEngMetalBldg { get; set; }
            public object PreEngMetalBldgOption { get; set; }
            public object DayCare { get; set; }
            public object ProfessionalCertification { get; set; }
            public object DownsizingSuiteOptions { get; set; }
            public object BFUndergroundPiping { get; set; }
            public object BFExtendPublicWaterSewer { get; set; }
            public object BFGradeChangeinEasement { get; set; }
            public object BFPreventer { get; set; }
            public object BFSprinklerPiping { get; set; }
            public object BFProposedEncroachmentInEasement { get; set; }
            public object PINNumber { get; set; }
            public object NewSepticTank { get; set; }
            public object NewPublicWater { get; set; }
            public object ExistingPublicWater { get; set; }
            public object ExistingPublicSewer { get; set; }
            public object NewPublicSewer { get; set; }
            public object ExistingWell { get; set; }
            public object NewWell { get; set; }
            public object ExistingSepticTank { get; set; }
            public object TotalNewHeatedSqFeet { get; set; }
            public object SqFtExistingTotal { get; set; }
            public object TotalRenovatedArea { get; set; }
        }

    }

