namespace Meck.Shared.Accela.ParserModels
{
    public class PreliminaryMeetingCustomForm
    {
        public object ProjectName { get; set; }
        public object IncludesAfforableOrWorkforceHousing { get; set; }
        public object WorkforceHousingUnits { get; set; }
        public string id { get; set; }
        public object AfforableHousingUnits { get; set; }
        public object BuildingCode { get; set; }
        public object PropertyType { get; set; }
        public object Agenda { get; set; }
        public object ProposedScopeOfWork { get; set; }
        public object CurrentReviewCycle { get; set; }
        public object ClonedFromProjectNumber { get; set; }
        public object IsRTAP { get; set; }
        public object TaxJurisdiction { get; set; }
        public object RecordLocation { get; set; }
        public object ProjectDeliveryMethodDesignBuild { get; set; }
        public object ProjectDeliveryMethodCMOwnerAgent { get; set; }
        public object BIMDisciplinesElec { get; set; }
        public object ProjectDeliveryMethodFastTrack { get; set; }
        public object ProjectDeliveryMethodOther { get; set; }
        public object ProjectDeliveryMethodDesignBidBuild { get; set; }
        public object ProjectDeliveryMethodIPDOrVariation { get; set; }
        public object PDMOtherDescription { get; set; }
        public object PDMDisciplinesDesignAssistMech { get; set; }
        public object PDMDisciplinesDesignBuildArchStruct { get; set; }
        public object BIMDisciplinesArch { get; set; }
        public object ProjectDeliveryMethodDesignAssist { get; set; }
        public object PDMDisciplinesDesignBuildMech { get; set; }
        public object PDMDisciplinesDesignBuildPlumb { get; set; }
        public object PDMDisciplinesDesignAssistArchStruct { get; set; }
        public object PDMDisciplinesDesignAssistElec { get; set; }
        public object ProjectIsBim { get; set; }
        public object PDMDisciplinesDesignBuildElec { get; set; }
        public object BIMDisciplinesStruct { get; set; }
        public object PDMDisciplinesDesignAssistPlumb { get; set; }
        public object BIMDisciplinesMech { get; set; }
        public object BIMDisciplinesPlumb { get; set; }
        public object UploadRequireDocumentation { get; set; }
        public object PINNumber { get; set; }
        public object TypeOfWorkUpfit { get; set; }
        public object TypeOfWorkNewConFull { get; set; }
        public object TypeOfWorkPreEngMetalBldgOption { get; set; }
        public object TypeOfWorkDayCare { get; set; }
        public object TypeOfWorkNewConShellFootFoundPrev { get; set; }
        public object TypeOfWorkProCert { get; set; }
        public object TypeOfWorkNewConShellFootFoundCore { get; set; }
        public object TypeOfWorkChangeOfUse { get; set; }
        public object TypeOfWorkNewConFootFound { get; set; }
        public object TypeOfWorkNewConShellFootFound { get; set; }
        public object TypeOfWorkPreEngMetalBldg { get; set; }
        public object TypeOfWorkNewConsShellFootFoundCorePrev { get; set; }
        public object TypeOfWorkAddition { get; set; }
        public object TypeOfWorkPrevOccupiedBldg { get; set; }
        public object RequestedEndDateRange { get; set; }
        public object RequestedBeginDateRange { get; set; }
        public object NumberOfAttendees { get; set; }
        public object PrelimTradeBackflow { get; set; }
        public object PrelimTradeReviewerBackflow { get; set; }
        public object PrelimTradeReviewerHealth { get; set; }
        public object PrelimTradeReviewerElectrical { get; set; }
        public object PrelimTradeZoning { get; set; }
        public object PrelimTradeReviewerBuilding { get; set; }
        public object PrelimTradeReviewerPlumbing { get; set; }
        public object PrelimTradeHealth { get; set; }
        public object PrelimTradeReviewerZoning { get; set; }
        public object PrelimTradeReviewerFire { get; set; }
        public object PrelimTradeMechanical { get; set; }
        public object TeamResponse { get; set; }
        public object PreviousPrelimProjectNumber { get; set; }
        public object PrelimTradeReviewerMechanical { get; set; }
        public object PreviousPrelimReview { get; set; }
        public object PrelimTradeElectrical { get; set; }
        public object PrelimTradeFire { get; set; }
        public object PrelimTradeBuilding { get; set; }
        public object PrelimTradePlumbing { get; set; }
    }
}
      