namespace Meck.Shared.Accela.ParserModels
{
    public class ResidentialProjectCustomForm
    {
        public string id { get; set; }
        public object HandicappedUnits { get; set; }
        public string SecondDuplexDeckArea { get; set; }
        public string SecondDuplexSubtradeTotal { get; set; }
        public string SecondDuplexBldgContractCost { get; set; }
        public object SecondDuplexUnheatedSqFt { get; set; }
        public string SecondDuplexHeatedSqFt { get; set; }
        public string CircuitsAt120Volts { get; set; }
        public string NumberOfCircuits { get; set; }
        public string TotalAmps { get; set; }
        public string CircuitsOver120Volts { get; set; }
        public string ElectricService { get; set; }
        public string PowerCompany { get; set; }
        public object UnheatedToHeatedSqFT { get; set; }
        public string NumberOfStories { get; set; }
        public string HasBasement { get; set; }
        public string HeatedSquareFeet { get; set; }
        public object RenovateSquareFeet { get; set; }
        public string ofUnits { get; set; }
        public object UnheatedSquareFeet { get; set; }
        public object ExpandedFootprint { get; set; }
        public string DeckArea { get; set; }
        public object LienAgentNumberEntryNumber { get; set; }
        public object BuildingCost { get; set; }
        public object SubtradeTotal { get; set; }
        public object ExpandedScopeOfWork { get; set; }
        public object CurrentReviewCycle { get; set; }
        public object ClonedFromProjectNumber { get; set; }
        public object IsRTAP { get; set; }
        public object TaxJurisdiction { get; set; }
        public object RecordLocation { get; set; }
        public object SolarPVSystemGTSingleLayerShingles { get; set; }
        public object SolarPVSystemWeightExcessive { get; set; }
        public object SolarPVRoofMountedInstallation { get; set; }
        public object SolarPVRoofMountedOption { get; set; }
        public object SolarPVSystemNonStandardRoofMats { get; set; }
        public object MasonryFireplace { get; set; }
        public object FireBuildingSprinkled { get; set; }
        public object InHomeDaycare { get; set; }
        public object HabitableSpaceAboveGarage { get; set; }
        public string NumberOfFixtures { get; set; }
        public string NumberOfPlumbingAppliances { get; set; }
        public object CommunitySeptic { get; set; }
        public object IndividualSeptic { get; set; }
        public object CommunityWell { get; set; }
        public object IndividualWell { get; set; }
        public object AddDormerIncreaseExistingHabitableSpace { get; set; }
        public object AddHabitableSpaceAboveGarage { get; set; }
        public object ExpandExistingRoofline { get; set; }
        public object AddHabitableSpaceAboveExistingStory { get; set; }
        public object AddDormerAddingHabitableSpace { get; set; }
        public object AddHabitableArea { get; set; }
        public object IncreaseExistingHabitableArea { get; set; }
        public string PropertyUse { get; set; }
        public object SFDwellingDetached { get; set; }
        public object HotTubSpaSafetyCover { get; set; }
        public object DockPier { get; set; }
        public string ProjectName { get; set; }
        public string AttachedGarage { get; set; }
        public object DetachedGarageTwoStories { get; set; }
        public object RetainingWall { get; set; }
        public object AddAdditionalStory { get; set; }
        public string TwoFamilyDwelling { get; set; }
        public object AttachedCarport { get; set; }
        public object AccessoryStructureWallGTOneStory { get; set; }
        public object DetachedCarport { get; set; }
        public object Pool { get; set; }
        public object HotTubSpa { get; set; }
        public object DetachedGarageOneStory { get; set; }
        public object RoomAddition { get; set; }
        public object AccessoryStructureWallOneStory { get; set; }
        public string TypeOfWork { get; set; }
        public object MobileHomeMoveOn { get; set; }
        public object ScreenedPorchOnly { get; set; }
        public object AccessoryStructureSleepingSpace { get; set; }
        public string Deck { get; set; }
        public object ElectricalOutletsWiring { get; set; }
        public object AccessoryDwellingUnit { get; set; }
        public object DetachedGarageSleepingSpace { get; set; }
        public object EncloseExistingDeck { get; set; }
        public object SFDwellingAttached { get; set; }
        public string BedroomAdditionUpfit { get; set; }
        public string Service { get; set; }
        public string MasterSewer { get; set; }
        public object IndividualSewer { get; set; }
        public object IndividualWater { get; set; }
        public string MasterWater { get; set; }
        public string Bedrooms { get; set; }
        public string TotalRooms { get; set; }
        public string Baths { get; set; }
        public object PendingMPProjectNumber { get; set; }
        public object TownhousePlanOptions { get; set; }
        public string ResidentialMPOptions { get; set; }
        public object ApprovedMPProjectNumber { get; set; }
        public object MPName { get; set; }
        public object PINNumber { get; set; }
        public object HeatPump { get; set; }
        public object ExhaustVentilation { get; set; }
        public object GasPack { get; set; }
        public object ElectricCeiling { get; set; }
        public string NumberOfGasConnections { get; set; }
        public object CentralAirConditioning { get; set; }
        public object Chimney { get; set; }
        public object PrefabricatedFireplace { get; set; }
        public object ElectricFurnace { get; set; }
        public object ElectricBaseboard { get; set; }
        public object Stove { get; set; }
        public string GasCompany { get; set; }
        public string NumberOfMechanicalAppliances { get; set; }
        public object RefrigerationOnly { get; set; }
        public string GasOrOilFurnace { get; set; }
        public string MechanicalTypeOfWork { get; set; }
        public string GasPiping { get; set; }
        public object GasOrOilSteam { get; set; }
    }
}
