ALTER PROCEDURE [AION].[usp_update_aion_cancel_reserve_express_reservation_v2]
	
AS

        --'Tentatively Scheduled'  
        DECLARE @TENTATIVE_APPT_RESPONSE_STATUS_REF_ID INT= 0;
        SELECT @TENTATIVE_APPT_RESPONSE_STATUS_REF_ID = APPT_RESPONSE_STATUS_REF_ID
        FROM AION.APPOINTMENT_RESPONSE_STATUS_REF
        WHERE ENUM_MAPPING_VAL_NBR = 9;  
        --  
        --'Cancelled'  
        DECLARE @CANCELLED_APPT_RESPONSE_STATUS_REF_ID INT= 0;
        SELECT @CANCELLED_APPT_RESPONSE_STATUS_REF_ID = APPT_RESPONSE_STATUS_REF_ID
        FROM AION.APPOINTMENT_RESPONSE_STATUS_REF
        WHERE ENUM_MAPPING_VAL_NBR = 7;  

        DECLARE @NowEST datetime

    SET @NowEST = CONVERT(datetime, SWITCHOFFSET(GETDATE(), DATEPART(TZOFFSET,
    GETDATE() AT TIME ZONE 'Eastern Standard Time')))

    DECLARE @Appts TABLE
        (
			RESERVE_EXPRESS_RESERVATION_ID INT
        )

INSERT INTO @Appts
        SELECT RESERVE_EXPRESS_RESERVATION_ID FROM AION.RESERVE_EXPRESS_RESERVATION RER WHERE APPT_RESPONSE_STATUS_REF_ID IN
		(SELECT APPT_RESPONSE_STATUS_REF_ID FROM AION.APPOINTMENT_RESPONSE_STATUS_REF WHERE APPT_RESPONSE_STATUS_DESC='Scheduled')
		AND @NowEST >= CANCEL_AFTER_DT

        UPDATE AION.RESERVE_EXPRESS_RESERVATION
		SET 
            APPT_RESPONSE_STATUS_REF_ID = @CANCELLED_APPT_RESPONSE_STATUS_REF_ID

		WHERE RESERVE_EXPRESS_RESERVATION_ID IN
		(SELECT RESERVE_EXPRESS_RESERVATION_ID FROM @Appts)

     SELECT RESERVE_EXPRESS_RESERVATION_ID FROM @Appts
   
RETURN
