ALTER PROCEDURE [AION].[usp_update_aion_cancel_facilitator_meeting_appointment_v2] 
	
AS

    DECLARE @NowEST datetime

    SET @NowEST = CONVERT(datetime, SWITCHOFFSET(GETDATE(), DATEPART(TZOFFSET,
    GETDATE() AT TIME ZONE 'Eastern Standard Time')))

    DECLARE @Appts TABLE
        (
			FACILITATOR_MEETING_APPT_IDENTIFIER INT
        )

    BEGIN  
        --'tentatively Scheduled'  
        DECLARE @APPT_RESPONSE_STATUS_REF_ID INT= 0;
        SELECT @APPT_RESPONSE_STATUS_REF_ID = APPT_RESPONSE_STATUS_REF_ID
        FROM AION.APPOINTMENT_RESPONSE_STATUS_REF
        WHERE ENUM_MAPPING_VAL_NBR = 9;  
        --  
        --'Cancelled'  
        DECLARE @CANCELLED_APPT_RESPONSE_STATUS_REF_ID INT= 0;

		SELECT @CANCELLED_APPT_RESPONSE_STATUS_REF_ID = APPT_RESPONSE_STATUS_REF_ID
        FROM AION.APPOINTMENT_RESPONSE_STATUS_REF
        WHERE ENUM_MAPPING_VAL_NBR = 7;  

        --'Cancellation Reason'  
        DECLARE @CANCELLED_APPT_REASON_REF_ID INT= 0;
        SELECT @CANCELLED_APPT_REASON_REF_ID = APPT_CANCELLATION_REF_ID
        FROM AION.APPOINTMENT_CANCELLATION_REF
        WHERE ENUM_MAPPING_VAL_NBR = 1;  

		INSERT INTO @Appts
		SELECT FACILITATOR_MEETING_APPT_IDENTIFIER
		FROM FACILITATOR_MEETING_APPOINTMENT
		WHERE APPT_RESPONSE_STATUS_REF_ID = @APPT_RESPONSE_STATUS_REF_ID
		AND @NowEST >= CANCEL_AFTER_DT 
  
        UPDATE AION.FACILITATOR_MEETING_APPOINTMENT
		SET
            APPT_RESPONSE_STATUS_REF_ID = @CANCELLED_APPT_RESPONSE_STATUS_REF_ID,
            APPT_CANCELLATION_REF_ID = @CANCELLED_APPT_REASON_REF_ID
		WHERE FACILITATOR_MEETING_APPT_IDENTIFIER IN
		(SELECT FACILITATOR_MEETING_APPT_IDENTIFIER FROM @Appts)
		
        --  
        SELECT FACILITATOR_MEETING_APPT_IDENTIFIER FROM @Appts
        RETURN;
    END;

