/***********************************************************************************************************************    
* Object:       usp_select_aion_project_get_list_by_status_ids    
* Description:  Retrieves Project list for given parameter(s).    
* Parameters:       
*               @prjStatusEnums                                                   varchar(50)   
*    
* Returns:      Recordset.    
* Comments:     Developer may need to manually join to other tables, P.such as code tables, P.to get additional info for retrieval.    
*               This proc expects id_person and/or id_file to generate list; modify as necessary.    
*               Include ORDER BY clause as necessary.    
* Version:      1.0    
* Created by:   AION_user    
* Created:      10/10/2019    
************************************************************************************************************************    
* Change History: Date, P.Name, P.Description    
* 10/10/2019    AION_user     Auto-generated    
* 04/26/2021 jlindsay add preliminary_ind       
* 07/08/2021	jlindsay add new field for Accela record id REC_ID_TXT
* 07/13/2021    jallen   add new field for Accela team score TEAM_GRADE_TXT
***********************************************************************************************************************/
ALTER PROCEDURE [AION].[usp_select_aion_project_get_list_by_status_ids] @prjStatusEnums VARCHAR(50)
AS
SELECT PROJECT_ID,
	P.PROJECT_NM,
	P.EXTERNAL_SYSTEM_REF_ID,
	P.WKR_ID_CREATED_TXT,
	P.CREATED_DTTM,
	P.WKR_ID_UPDATED_TXT,
	P.UPDATED_DTTM,
	P.PROJECT_STATUS_REF_ID,
	P.PROJECT_TYP_REF_ID,
	P.SRC_SYSTEM_VAL_TXT,
	P.TAG_CREATED_ID_NUM,
	P.TAG_CREATED_BY_TS,
	P.TAG_UPDATED_BY_TS,
	P.TAG_UPDATED_BY_ID_NUM,
	P.ASSIGNED_ESTIMATOR_ID,
	P.ASSIGNED_FACILITATOR_ID,
	P.PROJECT_MODE_REF_ID,
	P.WORKFLOW_STATUS_REF_ID,
	P.RTAP_IND,
	P.PRELIMINARY_IND,
	P.PROJECT_LVL_TXT,
	P.GATE_DT,
	P.PROJECT_ADDR_TXT,
	P.PROJECT_MANAGER_ID,
	P.BUILD_CONTR_NM,
	P.BUILD_CONTR_ACCT_NUM,
	P.GATE_ACCEPTED_IND,
	P.FIFO_DUE_DT,
	P.PLANS_READY_ON_DT,
	P.CYCLE_NBR,
	P.PRELIM_MEETING_COMPLETE_IND,
	P.ACCELA_RTAP_PROJECT_REF_ID,
	P.ACCELA_PRELIM_PROJECT_REF_ID,
	P.PROJECT_OCCUPANCY_TYP_MAP_NM,
	P.CONSTR_TYP_DESC,
	P.CONSTR_COST_AMT,
	P.SHEETS_CNT_DESC,
	P.SQUARE_FOOTAGE_TO_BE_REVIEWED_NBR,
	P.SQUARE_FOOTAGE_OF_OVERALL_BUILD_NBR,
	P.STORIES_CNT,
	P.HIGH_RISE_IND,
	P.EXPRESS_IND,
	P.REVIEW_TYP_REF_DESC,
	P.PRELIM_MEETING_CANCELLED_IND,
	P.FIFO_IND,
	P.TOTAL_JOB_COST_AMT,
	P.WORK_TYP_DESC,
	P.OCCUPANCY_DESC,
	P.PRI_OCCUPANCY_DESC,
	P.SECONDARY_OCCUPANCY_DESC,
	P.SEAL_HOLDERS_DESC,
	P.DESIGNER_DESC,
	P.FIRE_DETAIL_DESC,
	P.OVERALL_WORK_SCOPE_DESC,
	P.MECH_WORK_SCOPE_DESC,
	P.ELCTR_WORK_SCOPE_DESC,
	P.PLUMB_WORK_SCOPE_DESC,
	P.CIVIL_WORK_SCOPE_DESC,
	P.ZONING_OF_SITE_DESC,
	P.CHG_OF_USE_DESC,
	P.CONDITIONAL_PERMIT_APPROVAL_DESC,
	P.PREVIOUS_BUSINESS_TYP_DESC,
	P.CITY_OF_CHARLOTTE_DESC,
	P.PROPOSED_BUSINESS_TYP_DESC,
	P.CODE_SUMMARY_DESC,
	P.BACKFLOW_APPLICATION_DETAIL_DESC,
	P.WATER_SEWER_DETAIL_DESC,
	P.HEALTH_DEPT_DETAIL_DESC,
	P.DAY_CARE_DESC,
	P.PROPOSED_OUTDOOR_UNDERGROUND_PIPING_DESC,
	P.PROPOSED_FIRE_SPRINKLER_PIPING_DESC,
	P.INSTALL_CMUD_BACKFLOW_PREVENTER_DESC,
	P.EXTENDING_PUBLIC_WATER_SEWER_DESC,
	P.GRADE_MOD_WATER_SEWER_EASEMENT_DESC,
	P.PROPOSED_ENCROACHMENT_WATER_SEWER_EASEMENT_DESC,
	P.PARCEL_NUM,
	P.AFFORDABLE_HOUSING_DESC,
	P.EXACT_ADDR_TXT,
	P.DELIVERY_MTHD_DESC,
	P.BIM_DESC,
	P.BIM_DESIGN_DISCIPLINE_DESC,
	P.ATTENDEES_CNT_DESC,
	P.PREVIOUS_PRELIM_REVIEW_DESC,
	P.PROJECT_NUM_PREVIOUS_PRELIM_REVIEW_DESC,
	P.SAME_REVIEW_TEAM_DESC,
	P.PROPERTY_OWNER_NM,
	P.PROPERTY_OWNER_ADDR_TXT,
	P.PROPERTY_OWNER_EMAIL_ADDR_TXT,
	P.PROPERTY_OWNER_PHONE_NUM,
	P.PROPERTY_OWNER_AUTO_EMAIL_ADDR_TXT,
	P.PROPERTY_MANAGER_NM,
	P.PROPERTY_MANAGER_EMAIL_ADDR_TXT,
	P.PROPERTY_MANAGER_EMAIL_ADDR_2_TXT,
	P.ARCHITECT_DESIGNER_CNTCT_NM,
	P.ARCHITECT_DESIGNER_CNTCT_PHONE_NUM,
	P.ARCHITECT_DESIGNER_CNTCT_EMAIL_ADDR_TXT,
	P.ARCHITECT_DESIGNER_AUTO_EMAIL_ADDR_TXT,
	P.ARCHITECT_DRAWINGS_SEALED_DESC,
	P.ARCHITECT_DESIGNER_LICENSE_NUM,
	P.ARCHITECT_DESIGNER_LICENSE_BOARD_DESC,
	P.ARCHITECT_DESIGNER_EMPLOYEE_DESC,
	P.PERMIT_NUM,
	P.TOTAL_FEE_AMT,
	P.BUILD_CODE_VERSION_DESC,
	P.SQUARE_FOOTAGE_DESC,
	P.PROPERTY_MANAGER_PHONE_NUM,
	P.REC_ID_TXT,
	P.TEAM_GRADE_TXT
FROM PROJECT P
INNER JOIN PROJECT_STATUS_REF R ON P.[PROJECT_STATUS_REF_ID] = R.[PROJECT_STATUS_REF_ID]
WHERE R.ENUM_MAPPING_VAL_NBR IN (
		SELECT [value]
		FROM STRING_SPLIT(@prjStatusEnums, ',')
		)

RETURN
